# Use a imagem Nginx
FROM nginx:latest
LABEL authors="diegoneves"

# Copie o arquivo index.html para o diretório padrão do Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponha a porta 80
EXPOSE 80
